spring.application.name=user-mongo
spring.mongodb.uri=mongodb+srv://devsenior:vvJtqsJQTLnpcFwI@clusterusermongo.fwl4ibb.mongodb.net/user_mongo_db?appName=ClusterUserMongo
server.port=8081
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.devsenior=INFO