spring.application.name=user-mongo
spring.mongodb.uri=mongodb+srv://anaaalvarado19_db_user:nyh2MsWOKu59QXv6@cluster0clusterusermong.48idmij.mongodb.net/user_mongo_db?retryWrites=true&w=majority&appName=Cluster0ClusterUserMongo
server.port=8081
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.devsenior=INFO